apiVersion: v1
kind: PersistentVolume
metadata:
  name: neb0008-postgres-physpvc
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: neb0008-local-gafaelfawr
  claimRef:
    namespace: postgres
    name: postgres-physpvc
  local:
    path: /data/gafaelfawr/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - neb0008.slac.stanford.edu

