apiVersion: v1
kind: PersistentVolume
metadata:
  name: neb0004-standard-rwo
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard-rwo
  local:
    path: /data/standard-rwo/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - neb0004.slac.stanford.edu

